CareTrackerV1/Controllers/ClientController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CareTrackerV1.Models;
using CareTrackerV1.Controllers;
using Microsoft.AspNet.Identity;
using CareTrackerV1.ViewModel;

namespace CareTrackerV1.Controllers
{
    //[Authorize]

    public class ClientController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Client
        //[Authorize(Roles = "Admin, CareGiver, NextOfKin")]
        public ActionResult Index()
        {
           
            return View(db.Clients.ToList());

        }

        // GET: Client for CareGiver
        //[Authorize(Roles = "Admin, CareGiver, NextOfKin")]
        public ActionResult CareGiverIndex(string userID)
        {

            var viewModel = new ClientVisitUserData();

            viewModel.Clients = db.Clients.
                        Include(i => i.Visits).
                        Include(i => i.CareGivers);

            var UserID = userID;
            viewModel.Clients = db.CareGivers.
                                Where(i => i.UserID == userID).
                                Single().Clients;

            return View(viewModel);
        }

        // GET: Client for CareGiver
        //[Authorize(Roles = "Admin, CareGiver, NextOfKin")]
        public ActionResult NonAdminIndex(int? id)
        {
            var viewModel = new ClientVisitUserData();

            viewModel.Clients = db.Clients.
                        Include(i => i.Visits);

           /*viewModel.Clients = from v in db.Visits
                                   where
                                   (v.ClientID == id)
                                   where
                                   (v.CareGiverID == id.Value)
                                   select v;*/

            if (id != null)
            {
                ViewBag.ClientID = id.Value;
                viewModel.Visits = viewModel.Clients.
                    Where(i => i.ID == id.Value).Single().Visits;
            }

            return View(viewModel);
        }


        // GET: Client/Details/5
        [Authorize(Roles = "Admin")]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Client client = db.Clients.Find(id);
            if (client == null)
            {
                return HttpNotFound();
            }
            return View(client);
        }

        // GET: Client/Create
        //[Authorize(Roles = "Admin, CareGiver")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Client/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        //[Authorize(Roles = "Admin, CareGiver")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,FirstName,Surname,DOB,AddressLine1,AddressLine2,Region,PhoneNumber,Medication,HealthSummary,DoctorID,NextOfKinID")] Client client)
        {
            if (ModelState.IsValid)
            {
                db.Clients.Add(client);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(client);
        }

        // GET: Client/Edit/5
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Client client = db.Clients.Find(id);
            if (client == null)
            {
                return HttpNotFound();
            }
            return View(client);
        }

        // POST: Client/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,FirstName,Surname,DOB,AddressLine1,AddressLine2,Region,PhoneNumber,Medication,HealthSummary,DoctorID,NextOfKinID")] Client client)
        {
            if (ModelState.IsValid)
            {
                db.Entry(client).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(client);
        }

        // GET: Client/Delete/5
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Client client = db.Clients.Find(id);
            if (client == null)
            {
                return HttpNotFound();
            }
            return View(client);
        }

        // POST: Client/Delete/5
        [Authorize(Roles = "Admin")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Client client = db.Clients.Find(id);
            db.Clients.Remove(client);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CareTrackerV1/Controllers/VisitController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CareTrackerV1.Models;
using CareTrackerV1.ViewModel;

namespace CareTrackerV1.Controllers
{
    public class VisitController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Visit
        public ActionResult Index()
        {
            var visits = db.Visits.Include(c => c.CareGiver).Include(cl => cl.Client); // Including CareGiver and Client allows eager loading of names etc
            //return View(visits.ToList());
            return View(db.Visits.ToList());
        }

        public ActionResult CareGiverClientVisitIndex(int? id)
        {
            return View(db.Visits.ToList().Where(i => i.ClientID == id));
        }

        // GET: Visit/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Visit visit = db.Visits.Find(id);
            if (visit == null)
            {
                return HttpNotFound();
            }
            return View(visit);
        }

        // GET: Visit/Create
        public ActionResult Create()
        {
            ViewBag.CareGiverID = new SelectList(db.CareGivers, "ID", "FirstName");
            Visit visit = new Visit();
            ShowViewTaskData(visit);       //Gives checkbox options
            return View(visit);

        }

        private void ShowViewTaskData(Visit visit)                //Modified PopulateViewTaskData to remove 'pre-existing' tasks
        {
            var allVisitTasks = db.VisitTasks;
            var visitTasks = new HashSet<int>();
            var viewModel = new List<VisitTaskData>();
            foreach (var task in allVisitTasks)
            {
                viewModel.Add(new VisitTaskData
                {
                    VisitID = task.ID,
                    Description = task.Description,
                    Selected = visitTasks.Contains(task.ID)
                });
            }
            ViewBag.VisitTasks = viewModel;
        }

        // POST: Visit/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]

        public ActionResult Create(FormCollection formCollection, string[] selectedTasks)
        {

            var visitToCreate = new Visit();

            if (TryUpdateModel(visitToCreate, "",
      new string[] { "Time", "Date", "CareGiverID", "ClientID", "Details", "AlertType", "AlertDetails" }))
            {
                try
                {
                    CreateVisitTasks(selectedTasks, visitToCreate);

                    db.Entry(visitToCreate).State = EntityState.Added;
                    db.SaveChanges();

                    return RedirectToAction("Index");
                }
                catch (DataException /* dex */)
                {
                    //Log the error (uncomment dex variable name after DataException and add a line here to write a log.
                    ModelState.AddModelError("", "Code not working");
                }
            }
            ShowViewTaskData(visitToCreate);
            return View(visitToCreate);
        }

        private void CreateVisitTasks(string[] selectedTasks, Visit visitToCreate)
        {
            if (selectedTasks == null)
            {
                visitToCreate.VisitTasks = new List<VisitTask>();
                return;
            }

            var selectedTasksHS = new HashSet<string>(selectedTasks);
            var visitVisitTasks = new HashSet<int>(visitToCreate.VisitTasks.Select(t => t.ID));
            foreach (var visitTask in db.VisitTasks)
            {
                if (selectedTasksHS.Contains(visitTask.ID.ToString()))
                {
                    if (!visitVisitTasks.Contains(visitTask.ID))
                    {
                        visitToCreate.VisitTasks.Add(visitTask);
                    }
                }
                else
                {
                    if (visitVisitTasks.Contains(visitTask.ID))
                    {
                        visitToCreate.VisitTasks.Remove(visitTask);
                    }
                }
            }
        }

        // GET: Visit/Edit/5
        public ActionResult Edit(int? id)
        {
            
            Visit visit = db.Visits
                .Include(i => i.CareGiver)
                .Include(i => i.VisitTasks)
                .Where(i => i.ID == id)
                .Single();
            PopulateViewTaskData(visit);
            return View(visit);
        }

        private void PopulateViewTaskData(Visit visit)
        {
            var allVisitTasks = db.VisitTasks;
            var visitTasks = new HashSet<int>(visit.VisitTasks.Select(t => t.ID));
            var viewModel = new List<VisitTaskData>();
            foreach (var task in allVisitTasks)
            {
                viewModel.Add(new VisitTaskData
                {
                    VisitID = task.ID,
                    Description = task.Description,
                    Selected = visitTasks.Contains(task.ID)
                });
            }
            ViewBag.VisitTasks = viewModel;
        }

        // POST: Visit/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, FormCollection formCollection, string[] selectedTasks)
        {
            
            var visitToUpdate = db.Visits
                .Include(i => i.CareGiver)
                .Include(i => i.VisitTasks)
                .Where(i => i.ID == id)
                .Single();

            if (TryUpdateModel(visitToUpdate, "",
      new string[] { "Time", "Date", "CareGiverID", "ClientID", "Details", "AlertType", "AlertDetails" }))
            {
                try
                {
                    UpdateVisitTasks(selectedTasks, visitToUpdate);

                    db.Entry(visitToUpdate).State = EntityState.Modified;
                    db.SaveChanges();

                    return RedirectToAction("Index");
                }
                catch (DataException /* dex */)
                {
                    //Log the error (uncomment dex variable name after DataException and add a line here to write a log.
                    ModelState.AddModelError("", "Unable to save changes. Try again, and if the problem persists see your system administrator.");
                }
            }
            PopulateViewTaskData(visitToUpdate);
            return View(visitToUpdate);
        }

        private void UpdateVisitTasks(string[] selectedTasks, Visit visitToUpdate)
        {
            if (selectedTasks == null)
            {
                visitToUpdate.VisitTasks = new List<VisitTask>();
                return;
            }

            var selectedTasksHS = new HashSet<string>(selectedTasks);
            var visitVisitTasks = new HashSet<int>(visitToUpdate.VisitTasks.Select(t => t.ID));
            foreach (var visitTask in db.VisitTasks)
            {
                if (selectedTasksHS.Contains(visitTask.ID.ToString()))
                {
                    if (!visitVisitTasks.Contains(visitTask.ID))
                    {
                        visitToUpdate.VisitTasks.Add(visitTask);
                    }
                }
                else
                {
                    if (visitVisitTasks.Contains(visitTask.ID))
                    {
                        visitToUpdate.VisitTasks.Remove(visitTask);
                    }
                }
            }
        }
        // GET: Visit/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Visit visit = db.Visits.Find(id);
            if (visit == null)
            {
                return HttpNotFound();
            }
            return View(visit);
        }

        // POST: Visit/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Visit visit = db.Visits.Find(id);
            db.Visits.Remove(visit);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CareTrackerV1/Views/Client/CareGiverIndex.cshtml
@model CareTrackerV1.ViewModel.ClientVisitUserData

@{
    ViewBag.Title = "Clients";
}

<h3>Client List</h3>

<table class="table">

    <tr>
        <th>First Name</th>
        <th>Surname</th>
        <th>DOB</th>
    </tr>


    @foreach (var item in Model.Clients)
    {
        <tr>

            <td>
                @Html.DisplayFor(modelItem => item.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Surname)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DOB)
            </td>
            <td>
                @Html.ActionLink("Select", "CareGiverClientVisitIndex", "Visit", new { id = item.ID }, null)
            </td>
        </tr>
    }

</table>

CareTrackerV1/Views/Client/Create.cshtml
@model CareTrackerV1.Models.Client

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
                @Html.AntiForgeryToken()

                <div class="form-horizontal">
        <h4>Client</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Surname, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Surname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Surname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DOB, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DOB, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DOB, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AddressLine1, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AddressLine1, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AddressLine1, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AddressLine2, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AddressLine2, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AddressLine2, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Region, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.Region, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Region, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PhoneNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Medication, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Medication, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Medication, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HealthSummary, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HealthSummary, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HealthSummary, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DoctorID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DoctorID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DoctorID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NextOfKinID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NextOfKinID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NextOfKinID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CareTrackerV1/Views/Client/Delete.cshtml
@model CareTrackerV1.Models.Client

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Client</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Surname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Surname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DOB)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DOB)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AddressLine1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AddressLine1)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AddressLine2)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AddressLine2)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Region)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Region)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Medication)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Medication)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HealthSummary)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HealthSummary)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DoctorID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DoctorID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NextOfKinID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NextOfKinID)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

CareTrackerV1/Views/Client/Details.cshtml
@model CareTrackerV1.Models.Client

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Client</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Surname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Surname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DOB)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DOB)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AddressLine1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AddressLine1)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AddressLine2)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AddressLine2)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Region)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Region)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Medication)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Medication)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HealthSummary)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HealthSummary)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DoctorID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DoctorID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NextOfKinID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NextOfKinID)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

CareTrackerV1/Views/Client/Edit.cshtml
@model CareTrackerV1.Models.Client

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Client</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Surname, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Surname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Surname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DOB, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DOB, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DOB, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AddressLine1, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AddressLine1, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AddressLine1, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AddressLine2, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AddressLine2, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AddressLine2, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Region, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.Region, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Region, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PhoneNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Medication, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Medication, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Medication, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HealthSummary, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HealthSummary, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HealthSummary, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DoctorID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DoctorID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DoctorID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NextOfKinID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NextOfKinID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NextOfKinID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}