CareTrackerV1/Models/CareGiver.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using CareTrackerV1.Enums;
using System.ComponentModel.DataAnnotations.Schema;
using System.Web.Mvc;

namespace CareTrackerV1.Models
{
    public class CareGiver
    {
        public int ID { get; set; }    //PK

        [Required(ErrorMessage = "Please enter a value")]
        [Display(Name = "First Name *")]
        [StringLength(40, MinimumLength = 3, ErrorMessage = "First name minimum 3 characters, maximum 40 characters.")]
        [RegularExpression(@"^[a-zA-Z''-'\s]*$", ErrorMessage = "Disallowed characters used.")]
        public string FirstName { get; set; }

        [Required(ErrorMessage = "Please enter a value")]
        [Display(Name = "Surname *")]
        [StringLength(40, MinimumLength = 3, ErrorMessage = "Surname minimum 3 characters, maximum 40 characters.")]
        [RegularExpression(@"^[a-zA-Z''-'\s]*$", ErrorMessage = "Disallowed characters used.")]                        //Allows "'"
        public string Surname { get; set; }

        //[Required(ErrorMessage = "Please enter a value")]
        [Display(Name = "Address Line 1 *")]
        [StringLength(40, ErrorMessage = "Maximum number of characters allowed is 40")]
        public string AddressLine1 { get; set; }

        //[Display(Name = "Address Line 2")]
        [StringLength(40, ErrorMessage = "Maximum number of characters allowed is 40")]
        public string AddressLine2 { get; set; }

        //[Required]
        [Display(Name = "Region *")]
        public Region Region { get; set; }

        [Required]                              
        [Display(Name = "Email address")]
        [EmailAddress]
        public string Email { get; set; }

        //[Required]
        [Display(Name = "Phone number *")]
        [StringLength(20, ErrorMessage = "Maximum number length is 20")]
        [RegularExpression(@"^[+0-9\s]{1,20}$", ErrorMessage = "Please enter a valid phone number")]         //info found at https://msdn.microsoft.com/en-us/library/ff650303.aspx
        public string PhoneNumber { get; set; }

        //[Required]
        [Display(Name = "Mobile number *")]
        [StringLength(20, ErrorMessage = "Maximum number length is 20")]
        [RegularExpression(@"^[+0-9\s]{1,20}$", ErrorMessage = "Please enter a valid mobile number")]
        public string Mobile { get; set; }

        //[Required]
        [Display(Name = "Qualifications *")]     //*************HOW TO READ THIS IN???? SELECT FROM A LIST AND THEN SAVE A LIST OF QUALIFICATIONS PER CARE GIVER???
        public string Qualifications { get; set; }

        //[Required]
        [Display(Name = "CV *")]     //**************WANT THIS TO BE A TEXT FILE - HOW TO DO THIS?
        public string CV { get; set; }

        //[Required]
        [Display(Name = "References *")]     //********WANT THIS TO BE A TEXT FILE - HOW TO DO THIS?
        public string References { get; set; }

        //[Required]
        public string UserID { get; set; }      //FK for ApplicationUser

        //Navigation properties
        //One CareGiver could have many Clients - use ICollection
        public virtual ICollection<Client> Clients { get; set; }          //ASSOCIATIVE TABLE UNDER THE HOOD DEFINED IN IDENTITYMODEL

        //One CareGiver could have many Visits
        public virtual ICollection<Visit> Visits { get; set; }            //1-M FK REQUIRED IN VISIT TABLE

        //One CarGiver has one User ID
        [ForeignKey("UserID")]
        public virtual ApplicationUser User { get; set; }

        public IEnumerable<SelectListItem> AllClients { get; set; }

        private List<int> _selectedClients;
        public List<int> SelectedClients
        {
            get
            {
                if (_selectedClients == null)
                {
                    _selectedClients = Clients.Select(c => c.ID).ToList();
                }
                return _selectedClients;
            }
            set
            {
                _selectedClients = value;
            }
        }
        public virtual ICollection<File> Files { get; set; }
    }
}

CareTrackerV1/Controllers/CareGiverController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CareTrackerV1.Models;
using CareTrackerV1.ViewModel;

namespace CareTrackerV1.Controllers
{
    public class CareGiverController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: CareGiver
        public ActionResult Index(int? id, int? clientID)
        {
            var viewModel = new CareGiverIndexData();

            viewModel.CareGivers = db.CareGivers
                .Include(i => i.Clients)
                .Include(i => i.Visits)
                .OrderBy(i => i.Surname);

            

            if (id != null)
            {
                ViewBag.CareGiverID = id.Value;
                viewModel.Clients = viewModel.CareGivers.
                    Where(i => i.ID == id.Value).Single().Clients;

            }
            
            if (clientID != null)
            {
                ViewBag.ClientID = clientID.Value;

                viewModel.Visits = from v in db.Visits
                                   where
                                   (v.ClientID == clientID)
                                   where
                                   (v.CareGiverID == id.Value)
                                   select v;
           }

            return View(viewModel);

            }

        public ActionResult NonAdminIndex(int? id, int? clientID)
        {

            var viewModel = new CareGiverIndexData();

            viewModel.Clients = db.Clients
                .Include(i => i.CareGivers)
                .Include(i => i.Visits);

            if (id != null)
            {
                ViewBag.ClientID = clientID.Value;
                viewModel.Clients = viewModel.CareGivers.
                    Where(i => i.ID == id.Value).Single().Clients;
            }

            if (clientID != null)
            {
                ViewBag.ClientID = clientID.Value;

                viewModel.Visits = from v in db.Visits
                                   where
                                   (v.ClientID == clientID)
                                   where
                                   (v.CareGiverID == id.Value)
                                   select v;
            }

            /*if (clientID != null)
            {
                ViewBag.ClientID = clientID.Value;
                viewModel.Visits = viewModel.Clients.
                    Where(i => i.ID == clientID.Value).Single().Visits;
            }*/

            return View(viewModel);

        }

        // GET: CareGiver/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CareGiver careGiver = db.CareGivers.Include(c => c.Files).SingleOrDefault(c => c.ID == id);
            if (careGiver == null)
            {
                return HttpNotFound();
            }
            return View(careGiver);
        }

        // GET: CareGiver/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: CareGiver/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,FirstName,Surname,AddressLine1,AddressLine2,Region,Email,PhoneNumber,Mobile,Qualifications,CV,References")] CareGiver careGiver, HttpPostedFileBase upload)
        {
            if (ModelState.IsValid)
            {
                if (upload != null && upload.ContentLength > 0)
                {
                    var photoID = new File
                    {
                        FileName = System.IO.Path.GetFileName(upload.FileName),
                        FileType = FileType.PhotoID,
                        ContentType = upload.ContentType
                    };
                    using (var reader = new System.IO.BinaryReader(upload.InputStream))
                    {
                        photoID.Content = reader.ReadBytes(upload.ContentLength);
                    }
                    careGiver.Files = new List<File> { photoID };
                }
                db.CareGivers.Add(careGiver);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(careGiver);
        }

        // GET: CareGiver/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CareGiver careGiver = db.CareGivers.Include(c => c.Files).SingleOrDefault(c => c.ID == id);
            if (careGiver == null)
            {
                return HttpNotFound();
            }

            var allClientsList = db.Clients.ToList();
            careGiver.AllClients = allClientsList.Select(o => new SelectListItem
            {
                Text = o.FirstName + " " + o.Surname,
                Value = o.ID.ToString()
            });
            PopulateCareGiverClientData(careGiver);
            return View(careGiver);
        }

        private void PopulateCareGiverClientData(CareGiver careGiver)
        {
            var allClients = db.Clients;
            var clients = new HashSet<int>(careGiver.Clients.Select(c => c.ID));
            var viewModel = new List<CareGiverClientData>();
            foreach (var client in allClients)
            {
                viewModel.Add(new CareGiverClientData
                {
                    ClientID = client.ID,
                    Selected = clients.Contains(client.ID)
                });
            }
            ViewBag.Clients = viewModel;
        }

        // POST: CareGiver/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, FormCollection formCollection, string[] selectedClients, HttpPostedFileBase upload)
        {

            var careGiverToUpdate = db.CareGivers
                .Include(i => i.Clients)
                .Where(i => i.ID == id)
                .Single();

            if (TryUpdateModel(careGiverToUpdate, "",
      new string[] { "FirstName", "Surname", "AddressLine1", "AddressLine2", "Region", "Email", "PhoneNumber", "Mobile", "Qualifications", "CV", "References", "UserID" }))
            {
                /*try
                {
                    UpdateCareGiver(selectedClients, careGiverToUpdate);

                    db.Entry(careGiverToUpdate).State = EntityState.Modified;
                    db.SaveChanges();

                    return RedirectToAction("Index");
                }*/
                try
                {
                    if (upload != null && upload.ContentLength > 0)
                    {
                        if (careGiverToUpdate.Files.Any(f => f.FileType == FileType.PhotoID))
                        {
                            db.Files.Remove(careGiverToUpdate.Files.First(f => f.FileType == FileType.PhotoID));
                        }
                        var photoID = new File
                        {
                            FileName = System.IO.Path.GetFileName(upload.FileName),
                            FileType = FileType.PhotoID,
                            ContentType = upload.ContentType
                        };
                        using (var reader = new System.IO.BinaryReader(upload.InputStream))
                        {
                            photoID.Content = reader.ReadBytes(upload.ContentLength);
                        }
                        careGiverToUpdate.Files = new List<File> { photoID };
                    }

                    UpdateCareGiver(selectedClients, careGiverToUpdate);

                    db.Entry(careGiverToUpdate).State = EntityState.Modified;
                    db.SaveChanges();

                    return RedirectToAction("Index");
                }
                catch (DataException /* dex */)
                {
                    //Log the error (uncomment dex variable name after DataException and add a line here to write a log.
                    ModelState.AddModelError("", "Unable to save changes. Try again, and if the problem persists see your system administrator.");
                }
            }
            PopulateCareGiverClientData(careGiverToUpdate);
            return View(careGiverToUpdate);
        }

        private void UpdateCareGiver(string[] selectedClients, CareGiver careGiverToUpdate)
        {
            if (selectedClients == null)
            {
                careGiverToUpdate.Clients = new List<Client>();
                return;
            }

            var selectedClientsHS = new HashSet<string>(selectedClients);
            var careGiverClients = new HashSet<int>(careGiverToUpdate.Clients.Select(t => t.ID));
            foreach (var client in db.Clients)
            {
                if (selectedClientsHS.Contains(client.ID.ToString()))
                {
                    if (!careGiverClients.Contains(client.ID))
                    {
                        careGiverToUpdate.Clients.Add(client);
                    }
                }
                else
                {
                    if (careGiverClients.Contains(client.ID))
                    {
                        careGiverToUpdate.Clients.Remove(client);
                    }
                }
            }
        }

        // GET: CareGiver/Delete/5
        public ActionResult Delete(int? id)
        {

CareTrackerV1/Views/CareGiver/Create.cshtml
@model CareTrackerV1.Models.CareGiver

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm("Create", "CareGiver", null, FormMethod.Post, new { enctype = "multipart/form-data" })) 
{
                @Html.AntiForgeryToken()

                <div class="form-horizontal">
        <h4>CareGiver</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Surname, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Surname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Surname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AddressLine1, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AddressLine1, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AddressLine1, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AddressLine2, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AddressLine2, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AddressLine2, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Region, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.Region, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Region, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PhoneNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Mobile, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Mobile, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Mobile, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Qualifications, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Qualifications, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Qualifications, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CV, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CV, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CV, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.References, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.References, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.References, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("PhotoID", new { @class = "control-label col-md-2" })
             <div class="col-md-10">
                 <input type="file" id="PhotoID" name="upload" />
             </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

CareTrackerV1/Views/CareGiver/Delete.cshtml
@model CareTrackerV1.Models.CareGiver

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>CareGiver</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Surname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Surname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AddressLine1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AddressLine1)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AddressLine2)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AddressLine2)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Region)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Region)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Mobile)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Mobile)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Qualifications)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Qualifications)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CV)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CV)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.References)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.References)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

CareTrackerV1/Views/CareGiver/Details.cshtml
@model CareTrackerV1.Models.CareGiver

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>CareGiver</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Surname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Surname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AddressLine1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AddressLine1)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AddressLine2)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AddressLine2)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Region)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Region)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Mobile)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Mobile)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Qualifications)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Qualifications)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CV)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CV)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.References)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.References)
        </dd>

        @if (Model.Files.Any(f => f.FileType == CareTrackerV1.Models.FileType.PhotoID))
        {
            <dt>
                PhotoID
            </dt>
            <dd>
                <img src="~/File?id=@Model.Files.First(f => f.FileType == CareTrackerV1.Models.FileType.PhotoID).FileId" alt="photoID" />
            </dd>
        }
    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

CareTrackerV1/Views/CareGiver/Edit.cshtml
@model CareTrackerV1.Models.CareGiver

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm("Edit", "CareGiver", null, FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>CareGiver</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Surname, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Surname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Surname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AddressLine1, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AddressLine1, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AddressLine1, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AddressLine2, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AddressLine2, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AddressLine2, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Region, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.Region, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Region, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PhoneNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Mobile, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Mobile, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Mobile, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Qualifications, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Qualifications, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Qualifications, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CV, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CV, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CV, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.References, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.References, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.References, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AllClients, "Client", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.ListBoxFor(m => m.SelectedClients, Model.AllClients)
            </div>
        </div>

        @if (Model.Files.Any(f => f.FileType == CareTrackerV1.Models.FileType.PhotoID))
        {
            <div class="form-group">
                <span class="control-label col-md-2"><strong>Current Photo</strong></span>
                <div class="col-md-10">
                    <img src="~/File?id=@Model.Files.First(f => f.FileType == CareTrackerV1.Models.FileType.PhotoID).FileId" alt="photoID" />
                </div>
            </div>
        }
        <div class="form-group">
            @Html.Label("PhotoID", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" id="PhotoID" name="upload" />
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>